<a href="https://colab.research.google.com/github/xuandy05/Python-A.I./blob/master/NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NUMPY SPEED COMPARISON

In [0]:
k = 2
for i in range(30):
    k = k**2


In [0]:
import numpy as np
k = 2
for i in range(30):
    k = np.square(k)


### Creating a NumPy Array

In [0]:
#Example
a = np.array([1,2,3,1,23,1,2,3,2,34,5])

> Square all of the values in the array

In [0]:
import numpy as np
a = np.array([1,2,3,1,23,1,2,3,2,34,5])
a = np.square(a)
print(a)

[   1    4    9    1  529    1    4    9    4 1156   25]


Multiply the current array with the new array: <br>
> [1,2,3,4,6,1,2,3,4,5,6]

In [0]:
import numpy as np
a = np.array([1,2,3,1,23,1,2,3,2,34,5])
b = np.array([1,2,3,4,6,1,2,3,4,5,6])
print(a * b)

[  1   4   9   4 138   1   4   9   8 170  30]


### Create a 3x3 array of zeroes


In [0]:
import numpy as np
c = np.zeros((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


>  Add 10 to the every value

In [0]:
c + 10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])